### ISSUE TITLE
Get rid of sed dependency

### ISSUE THREAD

**Issue by DmitryTsepelev** [DmitryTsepelev/rubocop_director#5]

**Comment by samarthkathal** [comment]
Let me look into this

**Comment by samarthkathal** [comment]
Hi, @DmitryTsepelev there is only 1 instance where were are using `sed` [here](https://github.com/DmitryTsepelev/rubocop_director/blob/75a632fc42ad9851e4914ed932d0871320ad33d8/lib/rubocop_director/rubocop_stats.rb#L12). It is being used to remove all the lines from `.rubocop.yml` that contain `todo` it them.
We then parse it later as JSON using rubocop so that the parsed JSON config could later be used to generate stats.

There is an issue that I found while testing.
I had never committed my `.rubocop.yml` file to my current branch. In this case, `git checkout ./.rubocop.yml` [here](https://github.com/DmitryTsepelev/rubocop_director/blob/cda1e4ae85ae723b2e909f8fb64dda6ba4e09915/lib/rubocop_director/rubocop_stats.rb#L25) was not able to restore the previous version of `.rubocop.yml`.

We can make an in-memory copy of the config before modifying it and after we have parsed the file, we can restore it using the in-memory copy.

**Comment by samarthkathal** [comment]
what are your thoughts on this approach @DmitryTsepelev

**Comment by DmitryTsepelev** [comment]
> I had never committed my .rubocop.yml 
Tell me why 🙂 I usually keep it in the repo to have it shared between team members and run Rubocop on the CI as well

My initial plan (kudos @ilyasgaraev) was to:

- drop `sed`;
- instead of removing todo from the config, cleanup `.rubocop_todo.yml`
- checkout `.rubocop_todo.yml` after the command

**Comment by samarthkathal** [comment]
> I had never committed my .rubocop.yml

I initialized a new RoR project for testing and therefore forgot to commit it.

> I usually keep it in the repo to have it shared between team members and run Rubocop on the CI as well

This is the ideal practice that should be followed. However, at my current workplace, we had a project under accelerated development with a few RoR devs. Management, therefore, moved ahead by removing it from CI checks.

> Instead of removing todo from the config, cleanup .rubocop_todo.yml

Sorry, what kind of cleanup do you have in mind?

**Comment by DmitryTsepelev** [comment]
> I initialized a new RoR project for testing and therefore forgot to commit it.

Ah good point, would be nice to check that too and raise an error

> Management, therefore, moved ahead by removing it from CI checks.

May the force be with you!

> Sorry, what kind of cleanup do you have in mind?

The idea to just remove contents of the `.rubocop_todo.yml` before running the `rubocop` and then checkout it back. It can be done using Ruby, without messing with `sed`

**Comment by samarthkathal** [comment]
Luckily, I know the magic spell:
`bundle exec rubocop --auto-gen-config --auto-gen-only-exclude --no-exclude-limit` 😉

> The idea to just remove contents of the .rubocop_todo.yml before running the rubocop and then checkout it back. It can be done using Ruby, without messing with sed

To achieve this, we can remove the `.rubocop_todo.yml` line from `inherit_from:` block in `rubocop.yml` and then add it back. let me raise a PR for that
